version: '3.8'

services:
  fastapi:
    build: .
    container_name: mutelusys-fastapi
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./static:/app/static
      - ../design-media:/app/design-media
    restart: unless-stopped
    networks:
      - mutelusys-network

networks:
  mutelusys-network:
    external: true 