-- 插入全球国家数据（包含简体中文翻译）
-- 执行时间: 2025-06-25 17:17:48

-- 清空现有数据（如果需要重新导入）
-- DELETE FROM country_translations;
-- DELETE FROM country_regions;
-- DELETE FROM countries;

-- 插入国家数据
INSERT INTO countries (code, code3, name, native_name, currency, phone_code, status) VALUES
-- 亚洲国家
('CN', 'CHN', 'China', '中华人民共和国', 'CNY', '+86', 'active'),
('JP', 'JPN', 'Japan', '日本国', 'JPY', '+81', 'active'),
('KR', 'KOR', 'South Korea', '대한민국', 'KRW', '+82', 'active'),
('IN', 'IND', 'India', 'भारत', 'INR', '+91', 'active'),
('TH', 'THA', 'Thailand', 'ประเทศไทย', 'THB', '+66', 'active'),
('VN', 'VNM', 'Vietnam', 'Việt Nam', 'VND', '+84', 'active'),
('MY', 'MYS', 'Malaysia', 'Malaysia', 'MYR', '+60', 'active'),
('SG', 'SGP', 'Singapore', 'Singapore', 'SGD', '+65', 'active'),
('ID', 'IDN', 'Indonesia', 'Indonesia', 'IDR', '+62', 'active'),
('PH', 'PHL', 'Philippines', 'Pilipinas', 'PHP', '+63', 'active'),
('TW', 'TWN', 'Taiwan', '台灣', 'TWD', '+886', 'active'),
('HK', 'HKG', 'Hong Kong', '香港', 'HKD', '+852', 'active'),
('MO', 'MAC', 'Macao', '澳門', 'MOP', '+853', 'active'),
('BD', 'BGD', 'Bangladesh', 'বাংলাদেশ', 'BDT', '+880', 'active'),
('PK', 'PAK', 'Pakistan', 'پاکستان', 'PKR', '+92', 'active'),
('LK', 'LKA', 'Sri Lanka', 'ශ්‍රී ලංකා', 'LKR', '+94', 'active'),
('MM', 'MMR', 'Myanmar', 'မြန်မာ', 'MMK', '+95', 'active'),
('KH', 'KHM', 'Cambodia', 'កម្ពុជា', 'KHR', '+855', 'active'),
('LA', 'LAO', 'Laos', 'ລາວ', 'LAK', '+856', 'active'),
('BN', 'BRN', 'Brunei', 'Brunei', 'BND', '+673', 'active'),
('MN', 'MNG', 'Mongolia', 'Монгол', 'MNT', '+976', 'active'),
('NP', 'NPL', 'Nepal', 'नेपाल', 'NPR', '+977', 'active'),
('AF', 'AFG', 'Afghanistan', 'افغانستان', 'AFN', '+93', 'active'),
('IR', 'IRN', 'Iran', 'ایران', 'IRR', '+98', 'active'),
('IQ', 'IRQ', 'Iraq', 'العراق', 'IQD', '+964', 'active'),
('SA', 'SAU', 'Saudi Arabia', 'السعودية', 'SAR', '+966', 'active'),
('AE', 'ARE', 'United Arab Emirates', 'الإمارات', 'AED', '+971', 'active'),
('KW', 'KWT', 'Kuwait', 'الكويت', 'KWD', '+965', 'active'),
('QA', 'QAT', 'Qatar', 'قطر', 'QAR', '+974', 'active'),
('BH', 'BHR', 'Bahrain', 'البحرين', 'BHD', '+973', 'active'),
('OM', 'OMN', 'Oman', 'عُمان', 'OMR', '+968', 'active'),
('JO', 'JOR', 'Jordan', 'الأردن', 'JOD', '+962', 'active'),
('LB', 'LBN', 'Lebanon', 'لبنان', 'LBP', '+961', 'active'),
('SY', 'SYR', 'Syria', 'سوريا', 'SYP', '+963', 'active'),
('YE', 'YEM', 'Yemen', 'اليمن', 'YER', '+967', 'active'),
('IL', 'ISR', 'Israel', 'ישראל', 'ILS', '+972', 'active'),
('PS', 'PSE', 'Palestine', 'فلسطين', 'ILS', '+970', 'active'),
('TR', 'TUR', 'Turkey', 'Türkiye', 'TRY', '+90', 'active'),
('UZ', 'UZB', 'Uzbekistan', 'Oʻzbekiston', 'UZS', '+998', 'active'),
('KZ', 'KAZ', 'Kazakhstan', 'Қазақстан', 'KZT', '+7', 'active'),
('KG', 'KGZ', 'Kyrgyzstan', 'Кыргызстан', 'KGS', '+996', 'active'),
('TJ', 'TJK', 'Tajikistan', 'Тоҷикистон', 'TJS', '+992', 'active'),
('TM', 'TKM', 'Turkmenistan', 'Türkmenistan', 'TMT', '+993', 'active'),
('AM', 'ARM', 'Armenia', 'Հայաստան', 'AMD', '+374', 'active'),
('AZ', 'AZE', 'Azerbaijan', 'Azərbaycan', 'AZN', '+994', 'active'),
('GE', 'GEO', 'Georgia', 'საქართველო', 'GEL', '+995', 'active'),

-- 欧洲国家
('GB', 'GBR', 'United Kingdom', 'United Kingdom', 'GBP', '+44', 'active'),
('DE', 'DEU', 'Germany', 'Deutschland', 'EUR', '+49', 'active'),
('FR', 'FRA', 'France', 'France', 'EUR', '+33', 'active'),
('IT', 'ITA', 'Italy', 'Italia', 'EUR', '+39', 'active'),
('ES', 'ESP', 'Spain', 'España', 'EUR', '+34', 'active'),
('NL', 'NLD', 'Netherlands', 'Nederland', 'EUR', '+31', 'active'),
('BE', 'BEL', 'Belgium', 'België', 'EUR', '+32', 'active'),
('CH', 'CHE', 'Switzerland', 'Schweiz', 'CHF', '+41', 'active'),
('AT', 'AUT', 'Austria', 'Österreich', 'EUR', '+43', 'active'),
('SE', 'SWE', 'Sweden', 'Sverige', 'SEK', '+46', 'active'),
('NO', 'NOR', 'Norway', 'Norge', 'NOK', '+47', 'active'),
('DK', 'DNK', 'Denmark', 'Danmark', 'DKK', '+45', 'active'),
('FI', 'FIN', 'Finland', 'Suomi', 'EUR', '+358', 'active'),
('IS', 'ISL', 'Iceland', 'Ísland', 'ISK', '+354', 'active'),
('IE', 'IRL', 'Ireland', 'Éire', 'EUR', '+353', 'active'),
('PT', 'PRT', 'Portugal', 'Portugal', 'EUR', '+351', 'active'),
('GR', 'GRC', 'Greece', 'Ελλάδα', 'EUR', '+30', 'active'),
('PL', 'POL', 'Poland', 'Polska', 'PLN', '+48', 'active'),
('CZ', 'CZE', 'Czech Republic', 'Česko', 'CZK', '+420', 'active'),
('SK', 'SVK', 'Slovakia', 'Slovensko', 'EUR', '+421', 'active'),
('HU', 'HUN', 'Hungary', 'Magyarország', 'HUF', '+36', 'active'),
('RO', 'ROU', 'Romania', 'România', 'RON', '+40', 'active'),
('BG', 'BGR', 'Bulgaria', 'България', 'BGN', '+359', 'active'),
('HR', 'HRV', 'Croatia', 'Hrvatska', 'EUR', '+385', 'active'),
('SI', 'SVN', 'Slovenia', 'Slovenija', 'EUR', '+386', 'active'),
('LT', 'LTU', 'Lithuania', 'Lietuva', 'EUR', '+370', 'active'),
('LV', 'LVA', 'Latvia', 'Latvija', 'EUR', '+371', 'active'),
('EE', 'EST', 'Estonia', 'Eesti', 'EUR', '+372', 'active'),
('RU', 'RUS', 'Russia', 'Россия', 'RUB', '+7', 'active'),
('UA', 'UKR', 'Ukraine', 'Україна', 'UAH', '+380', 'active'),
('BY', 'BLR', 'Belarus', 'Беларусь', 'BYN', '+375', 'active'),
('MD', 'MDA', 'Moldova', 'Moldova', 'MDL', '+373', 'active'),
('RS', 'SRB', 'Serbia', 'Србија', 'RSD', '+381', 'active'),
('BA', 'BIH', 'Bosnia and Herzegovina', 'Bosna i Hercegovina', 'BAM', '+387', 'active'),
('ME', 'MNE', 'Montenegro', 'Crna Gora', 'EUR', '+382', 'active'),
('MK', 'MKD', 'North Macedonia', 'Северна Македонија', 'MKD', '+389', 'active'),
('AL', 'ALB', 'Albania', 'Shqipëria', 'ALL', '+355', 'active'),
('XK', 'XKX', 'Kosovo', 'Kosova', 'EUR', '+383', 'active'),
('LU', 'LUX', 'Luxembourg', 'Luxembourg', 'EUR', '+352', 'active'),
('MT', 'MLT', 'Malta', 'Malta', 'EUR', '+356', 'active'),
('CY', 'CYP', 'Cyprus', 'Κύπρος', 'EUR', '+357', 'active'),

-- 北美洲国家
('US', 'USA', 'United States', 'United States', 'USD', '+1', 'active'),
('CA', 'CAN', 'Canada', 'Canada', 'CAD', '+1', 'active'),
('MX', 'MEX', 'Mexico', 'México', 'MXN', '+52', 'active'),
('GT', 'GTM', 'Guatemala', 'Guatemala', 'GTQ', '+502', 'active'),
('BZ', 'BLZ', 'Belize', 'Belize', 'BZD', '+501', 'active'),
('SV', 'SLV', 'El Salvador', 'El Salvador', 'USD', '+503', 'active'),
('HN', 'HND', 'Honduras', 'Honduras', 'HNL', '+504', 'active'),
('NI', 'NIC', 'Nicaragua', 'Nicaragua', 'NIO', '+505', 'active'),
('CR', 'CRI', 'Costa Rica', 'Costa Rica', 'CRC', '+506', 'active'),
('PA', 'PAN', 'Panama', 'Panamá', 'PAB', '+507', 'active'),

-- 南美洲国家
('BR', 'BRA', 'Brazil', 'Brasil', 'BRL', '+55', 'active'),
('AR', 'ARG', 'Argentina', 'Argentina', 'ARS', '+54', 'active'),
('CL', 'CHL', 'Chile', 'Chile', 'CLP', '+56', 'active'),
('PE', 'PER', 'Peru', 'Perú', 'PEN', '+51', 'active'),
('CO', 'COL', 'Colombia', 'Colombia', 'COP', '+57', 'active'),
('VE', 'VEN', 'Venezuela', 'Venezuela', 'VES', '+58', 'active'),
('EC', 'ECU', 'Ecuador', 'Ecuador', 'USD', '+593', 'active'),
('BO', 'BOL', 'Bolivia', 'Bolivia', 'BOB', '+591', 'active'),
('PY', 'PRY', 'Paraguay', 'Paraguay', 'PYG', '+595', 'active'),
('UY', 'URY', 'Uruguay', 'Uruguay', 'UYU', '+598', 'active'),
('GY', 'GUY', 'Guyana', 'Guyana', 'GYD', '+592', 'active'),
('SR', 'SUR', 'Suriname', 'Suriname', 'SRD', '+597', 'active'),

-- 非洲国家
('EG', 'EGY', 'Egypt', 'مصر', 'EGP', '+20', 'active'),
('ZA', 'ZAF', 'South Africa', 'South Africa', 'ZAR', '+27', 'active'),
('NG', 'NGA', 'Nigeria', 'Nigeria', 'NGN', '+234', 'active'),
('KE', 'KEN', 'Kenya', 'Kenya', 'KES', '+254', 'active'),
('GH', 'GHA', 'Ghana', 'Ghana', 'GHS', '+233', 'active'),
('MA', 'MAR', 'Morocco', 'المغرب', 'MAD', '+212', 'active'),
('TN', 'TUN', 'Tunisia', 'تونس', 'TND', '+216', 'active'),
('DZ', 'DZA', 'Algeria', 'الجزائر', 'DZD', '+213', 'active'),
('LY', 'LBY', 'Libya', 'ليبيا', 'LYD', '+218', 'active'),
('SD', 'SDN', 'Sudan', 'السودان', 'SDG', '+249', 'active'),
('ET', 'ETH', 'Ethiopia', 'ኢትዮጵያ', 'ETB', '+251', 'active'),
('UG', 'UGA', 'Uganda', 'Uganda', 'UGX', '+256', 'active'),
('TZ', 'TZA', 'Tanzania', 'Tanzania', 'TZS', '+255', 'active'),
('ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'ZWL', '+263', 'active'),
('BW', 'BWA', 'Botswana', 'Botswana', 'BWP', '+267', 'active'),
('ZM', 'ZMB', 'Zambia', 'Zambia', 'ZMW', '+260', 'active'),
('MW', 'MWI', 'Malawi', 'Malawi', 'MWK', '+265', 'active'),
('MZ', 'MOZ', 'Mozambique', 'Moçambique', 'MZN', '+258', 'active'),
('NA', 'NAM', 'Namibia', 'Namibia', 'NAD', '+264', 'active'),
('SZ', 'SWZ', 'Eswatini', 'eSwatini', 'SZL', '+268', 'active'),
('LS', 'LSO', 'Lesotho', 'Lesotho', 'LSL', '+266', 'active'),
('RW', 'RWA', 'Rwanda', 'Rwanda', 'RWF', '+250', 'active'),
('BI', 'BDI', 'Burundi', 'Burundi', 'BIF', '+257', 'active'),
('DJ', 'DJI', 'Djibouti', 'جيبوتي', 'DJF', '+253', 'active'),
('SO', 'SOM', 'Somalia', 'Soomaaliya', 'SOS', '+252', 'active'),
('ER', 'ERI', 'Eritrea', 'ኤርትራ', 'ERN', '+291', 'active'),
('CF', 'CAF', 'Central African Republic', 'Centrafrique', 'XAF', '+236', 'active'),
('TD', 'TCD', 'Chad', 'تشاد', 'XAF', '+235', 'active'),
('CM', 'CMR', 'Cameroon', 'Cameroun', 'XAF', '+237', 'active'),
('GA', 'GAB', 'Gabon', 'Gabon', 'XAF', '+241', 'active'),
('GQ', 'GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial', 'XAF', '+240', 'active'),
('CG', 'COG', 'Republic of the Congo', 'Congo', 'XAF', '+242', 'active'),
('CD', 'COD', 'Democratic Republic of the Congo', 'République démocratique du Congo', 'CDF', '+243', 'active'),
('AO', 'AGO', 'Angola', 'Angola', 'AOA', '+244', 'active'),
('SN', 'SEN', 'Senegal', 'Sénégal', 'XOF', '+221', 'active'),
('ML', 'MLI', 'Mali', 'Mali', 'XOF', '+223', 'active'),
('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'XOF', '+226', 'active'),
('NE', 'NER', 'Niger', 'Niger', 'XOF', '+227', 'active'),
('CI', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire', 'XOF', '+225', 'active'),
('LR', 'LBR', 'Liberia', 'Liberia', 'LRD', '+231', 'active'),
('SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'SLL', '+232', 'active'),
('GN', 'GIN', 'Guinea', 'Guinée', 'GNF', '+224', 'active'),
('GW', 'GNB', 'Guinea-Bissau', 'Guiné-Bissau', 'XOF', '+245', 'active'),
('GM', 'GMB', 'Gambia', 'Gambia', 'GMD', '+220', 'active'),
('CV', 'CPV', 'Cape Verde', 'Cabo Verde', 'CVE', '+238', 'active'),
('ST', 'STP', 'São Tomé and Príncipe', 'São Tomé e Príncipe', 'STN', '+239', 'active'),
('MG', 'MDG', 'Madagascar', 'Madagasikara', 'MGA', '+261', 'active'),
('MU', 'MUS', 'Mauritius', 'Maurice', 'MUR', '+230', 'active'),
('SC', 'SYC', 'Seychelles', 'Seychelles', 'SCR', '+248', 'active'),
('KM', 'COM', 'Comoros', 'جزر القمر', 'KMF', '+269', 'active'),
('MR', 'MRT', 'Mauritania', 'موريتانيا', 'MRU', '+222', 'active'),

-- 大洋洲国家
('AU', 'AUS', 'Australia', 'Australia', 'AUD', '+61', 'active'),
('NZ', 'NZL', 'New Zealand', 'New Zealand', 'NZD', '+64', 'active'),
('FJ', 'FJI', 'Fiji', 'Fiji', 'FJD', '+679', 'active'),
('PG', 'PNG', 'Papua New Guinea', 'Papua New Guinea', 'PGK', '+675', 'active'),
('SB', 'SLB', 'Solomon Islands', 'Solomon Islands', 'SBD', '+677', 'active'),
('VU', 'VUT', 'Vanuatu', 'Vanuatu', 'VUV', '+678', 'active'),
('NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie', 'XPF', '+687', 'active'),
('PF', 'PYF', 'French Polynesia', 'Polynésie française', 'XPF', '+689', 'active'),
('WS', 'WSM', 'Samoa', 'Samoa', 'WST', '+685', 'active'),
('TO', 'TON', 'Tonga', 'Tonga', 'TOP', '+676', 'active'),
('KI', 'KIR', 'Kiribati', 'Kiribati', 'AUD', '+686', 'active'),
('TV', 'TUV', 'Tuvalu', 'Tuvalu', 'AUD', '+688', 'active'),
('NR', 'NRU', 'Nauru', 'Nauru', 'AUD', '+674', 'active'),
('PW', 'PLW', 'Palau', 'Palau', 'USD', '+680', 'active'),
('FM', 'FSM', 'Micronesia', 'Micronesia', 'USD', '+691', 'active'),
('MH', 'MHL', 'Marshall Islands', 'Marshall Islands', 'USD', '+692', 'active'),

-- 加勒比海和其他地区
('JM', 'JAM', 'Jamaica', 'Jamaica', 'JMD', '+1876', 'active'),
('CU', 'CUB', 'Cuba', 'Cuba', 'CUP', '+53', 'active'),
('HT', 'HTI', 'Haiti', 'Haïti', 'HTG', '+509', 'active'),
('DO', 'DOM', 'Dominican Republic', 'República Dominicana', 'DOP', '+1809', 'active'),
('TT', 'TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', 'TTD', '+1868', 'active'),
('BB', 'BRB', 'Barbados', 'Barbados', 'BBD', '+1246', 'active'),
('LC', 'LCA', 'Saint Lucia', 'Saint Lucia', 'XCD', '+1758', 'active'),
('GD', 'GRD', 'Grenada', 'Grenada', 'XCD', '+1473', 'active'),
('VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'XCD', '+1784', 'active'),
('AG', 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'XCD', '+1268', 'active'),
('DM', 'DMA', 'Dominica', 'Dominica', 'XCD', '+1767', 'active'),
('KN', 'KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'XCD', '+1869', 'active'),
('BS', 'BHS', 'Bahamas', 'Bahamas', 'BSD', '+1242', 'active'),

-- 特殊地区和地区
('PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'USD', '+1787', 'active'),
('VI', 'VIR', 'U.S. Virgin Islands', 'U.S. Virgin Islands', 'USD', '+1340', 'active'),
('GU', 'GUM', 'Guam', 'Guam', 'USD', '+1671', 'active'),
('AS', 'ASM', 'American Samoa', 'American Samoa', 'USD', '+1684', 'active'),
('MP', 'MNP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'USD', '+1670', 'active'),
('UM', 'UMI', 'U.S. Minor Outlying Islands', 'U.S. Minor Outlying Islands', 'USD', '', 'active'),
('GI', 'GIB', 'Gibraltar', 'Gibraltar', 'GIP', '+350', 'active'),
('IM', 'IMN', 'Isle of Man', 'Isle of Man', 'GBP', '+44', 'active'),
('JE', 'JEY', 'Jersey', 'Jersey', 'GBP', '+44', 'active'),
('GG', 'GGY', 'Guernsey', 'Guernsey', 'GBP', '+44', 'active'),
('FO', 'FRO', 'Faroe Islands', 'Føroyar', 'DKK', '+298', 'active'),
('GL', 'GRL', 'Greenland', 'Kalaallit Nunaat', 'DKK', '+299', 'active'),
('AX', 'ALA', 'Åland Islands', 'Åland', 'EUR', '+358', 'active'),
('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'NOK', '+47', 'active'),
('BV', 'BVT', 'Bouvet Island', 'Bouvet Island', 'NOK', '', 'active'),
('HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'AUD', '', 'active'),
('TF', 'ATF', 'French Southern Territories', 'Terres australes françaises', 'EUR', '', 'active'),
('IO', 'IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'USD', '+246', 'active'),
('CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'AUD', '+891', 'active'),
('CX', 'CXR', 'Christmas Island', 'Christmas Island', 'AUD', '+61', 'active'),
('NF', 'NFK', 'Norfolk Island', 'Norfolk Island', 'AUD', '+672', 'active'),
('PN', 'PCN', 'Pitcairn', 'Pitcairn', 'NZD', '+64', 'active'),
('SH', 'SHN', 'Saint Helena', 'Saint Helena', 'SHP', '+290', 'active'),
('TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'USD', '+1649', 'active'),
('VG', 'VGB', 'British Virgin Islands', 'British Virgin Islands', 'USD', '+1284', 'active'),
('FK', 'FLK', 'Falkland Islands', 'Falkland Islands', 'FKP', '+500', 'active'),
('GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'GBP', '', 'active');

-- 插入中文翻译
INSERT INTO country_translations (country_id, language, name) VALUES
-- 获取国家ID并插入翻译（以下使用子查询）
((SELECT id FROM countries WHERE code = 'CN'), 'zh-CN', '中国'),
((SELECT id FROM countries WHERE code = 'JP'), 'zh-CN', '日本'),
((SELECT id FROM countries WHERE code = 'KR'), 'zh-CN', '韩国'),
((SELECT id FROM countries WHERE code = 'IN'), 'zh-CN', '印度'),
((SELECT id FROM countries WHERE code = 'TH'), 'zh-CN', '泰国'),
((SELECT id FROM countries WHERE code = 'VN'), 'zh-CN', '越南'),
((SELECT id FROM countries WHERE code = 'MY'), 'zh-CN', '马来西亚'),
((SELECT id FROM countries WHERE code = 'SG'), 'zh-CN', '新加坡'),
((SELECT id FROM countries WHERE code = 'ID'), 'zh-CN', '印度尼西亚'),
((SELECT id FROM countries WHERE code = 'PH'), 'zh-CN', '菲律宾'),
((SELECT id FROM countries WHERE code = 'TW'), 'zh-CN', '台湾'),
((SELECT id FROM countries WHERE code = 'HK'), 'zh-CN', '香港'),
((SELECT id FROM countries WHERE code = 'MO'), 'zh-CN', '澳门'),
((SELECT id FROM countries WHERE code = 'BD'), 'zh-CN', '孟加拉国'),
((SELECT id FROM countries WHERE code = 'PK'), 'zh-CN', '巴基斯坦'),
((SELECT id FROM countries WHERE code = 'LK'), 'zh-CN', '斯里兰卡'),
((SELECT id FROM countries WHERE code = 'MM'), 'zh-CN', '缅甸'),
((SELECT id FROM countries WHERE code = 'KH'), 'zh-CN', '柬埔寨'),
((SELECT id FROM countries WHERE code = 'LA'), 'zh-CN', '老挝'),
((SELECT id FROM countries WHERE code = 'BN'), 'zh-CN', '文莱'),
((SELECT id FROM countries WHERE code = 'MN'), 'zh-CN', '蒙古'),
((SELECT id FROM countries WHERE code = 'NP'), 'zh-CN', '尼泊尔'),
((SELECT id FROM countries WHERE code = 'AF'), 'zh-CN', '阿富汗'),
((SELECT id FROM countries WHERE code = 'IR'), 'zh-CN', '伊朗'),
((SELECT id FROM countries WHERE code = 'IQ'), 'zh-CN', '伊拉克'),
((SELECT id FROM countries WHERE code = 'SA'), 'zh-CN', '沙特阿拉伯'),
((SELECT id FROM countries WHERE code = 'AE'), 'zh-CN', '阿联酋'),
((SELECT id FROM countries WHERE code = 'KW'), 'zh-CN', '科威特'),
((SELECT id FROM countries WHERE code = 'QA'), 'zh-CN', '卡塔尔'),
((SELECT id FROM countries WHERE code = 'BH'), 'zh-CN', '巴林'),
((SELECT id FROM countries WHERE code = 'OM'), 'zh-CN', '阿曼'),
((SELECT id FROM countries WHERE code = 'JO'), 'zh-CN', '约旦'),
((SELECT id FROM countries WHERE code = 'LB'), 'zh-CN', '黎巴嫩'),
((SELECT id FROM countries WHERE code = 'SY'), 'zh-CN', '叙利亚'),
((SELECT id FROM countries WHERE code = 'YE'), 'zh-CN', '也门'),
((SELECT id FROM countries WHERE code = 'IL'), 'zh-CN', '以色列'),
((SELECT id FROM countries WHERE code = 'PS'), 'zh-CN', '巴勒斯坦'),
((SELECT id FROM countries WHERE code = 'TR'), 'zh-CN', '土耳其'),
((SELECT id FROM countries WHERE code = 'UZ'), 'zh-CN', '乌兹别克斯坦'),
((SELECT id FROM countries WHERE code = 'KZ'), 'zh-CN', '哈萨克斯坦'),
((SELECT id FROM countries WHERE code = 'KG'), 'zh-CN', '吉尔吉斯斯坦'),
((SELECT id FROM countries WHERE code = 'TJ'), 'zh-CN', '塔吉克斯坦'),
((SELECT id FROM countries WHERE code = 'TM'), 'zh-CN', '土库曼斯坦'),
((SELECT id FROM countries WHERE code = 'AM'), 'zh-CN', '亚美尼亚'),
((SELECT id FROM countries WHERE code = 'AZ'), 'zh-CN', '阿塞拜疆'),
((SELECT id FROM countries WHERE code = 'GE'), 'zh-CN', '格鲁吉亚'),

-- 欧洲国家
((SELECT id FROM countries WHERE code = 'GB'), 'zh-CN', '英国'),
((SELECT id FROM countries WHERE code = 'DE'), 'zh-CN', '德国'),
((SELECT id FROM countries WHERE code = 'FR'), 'zh-CN', '法国'),
((SELECT id FROM countries WHERE code = 'IT'), 'zh-CN', '意大利'),
((SELECT id FROM countries WHERE code = 'ES'), 'zh-CN', '西班牙'),
((SELECT id FROM countries WHERE code = 'NL'), 'zh-CN', '荷兰'),
((SELECT id FROM countries WHERE code = 'BE'), 'zh-CN', '比利时'),
((SELECT id FROM countries WHERE code = 'CH'), 'zh-CN', '瑞士'),
((SELECT id FROM countries WHERE code = 'AT'), 'zh-CN', '奥地利'),
((SELECT id FROM countries WHERE code = 'SE'), 'zh-CN', '瑞典'),
((SELECT id FROM countries WHERE code = 'NO'), 'zh-CN', '挪威'),
((SELECT id FROM countries WHERE code = 'DK'), 'zh-CN', '丹麦'),
((SELECT id FROM countries WHERE code = 'FI'), 'zh-CN', '芬兰'),
((SELECT id FROM countries WHERE code = 'IS'), 'zh-CN', '冰岛'),
((SELECT id FROM countries WHERE code = 'IE'), 'zh-CN', '爱尔兰'),
((SELECT id FROM countries WHERE code = 'PT'), 'zh-CN', '葡萄牙'),
((SELECT id FROM countries WHERE code = 'GR'), 'zh-CN', '希腊'),
((SELECT id FROM countries WHERE code = 'PL'), 'zh-CN', '波兰'),
((SELECT id FROM countries WHERE code = 'CZ'), 'zh-CN', '捷克'),
((SELECT id FROM countries WHERE code = 'SK'), 'zh-CN', '斯洛伐克'),
((SELECT id FROM countries WHERE code = 'HU'), 'zh-CN', '匈牙利'),
((SELECT id FROM countries WHERE code = 'RO'), 'zh-CN', '罗马尼亚'),
((SELECT id FROM countries WHERE code = 'BG'), 'zh-CN', '保加利亚'),
((SELECT id FROM countries WHERE code = 'HR'), 'zh-CN', '克罗地亚'),
((SELECT id FROM countries WHERE code = 'SI'), 'zh-CN', '斯洛文尼亚'),
((SELECT id FROM countries WHERE code = 'LT'), 'zh-CN', '立陶宛'),
((SELECT id FROM countries WHERE code = 'LV'), 'zh-CN', '拉脱维亚'),
((SELECT id FROM countries WHERE code = 'EE'), 'zh-CN', '爱沙尼亚'),
((SELECT id FROM countries WHERE code = 'RU'), 'zh-CN', '俄国'),
((SELECT id FROM countries WHERE code = 'UA'), 'zh-CN', '乌克兰'),
((SELECT id FROM countries WHERE code = 'BY'), 'zh-CN', '白俄罗斯'),
((SELECT id FROM countries WHERE code = 'MD'), 'zh-CN', '摩尔多瓦'),
((SELECT id FROM countries WHERE code = 'RS'), 'zh-CN', '塞尔维亚'),
((SELECT id FROM countries WHERE code = 'BA'), 'zh-CN', '波黑'),
((SELECT id FROM countries WHERE code = 'ME'), 'zh-CN', '黑山'),
((SELECT id FROM countries WHERE code = 'MK'), 'zh-CN', '北马其顿'),
((SELECT id FROM countries WHERE code = 'AL'), 'zh-CN', '阿尔巴尼亚'),
((SELECT id FROM countries WHERE code = 'XK'), 'zh-CN', '科索沃'),
((SELECT id FROM countries WHERE code = 'LU'), 'zh-CN', '卢森堡'),
((SELECT id FROM countries WHERE code = 'MT'), 'zh-CN', '马耳他'),
((SELECT id FROM countries WHERE code = 'CY'), 'zh-CN', '塞浦路斯'),

-- 北美洲国家
((SELECT id FROM countries WHERE code = 'US'), 'zh-CN', '美国'),
((SELECT id FROM countries WHERE code = 'CA'), 'zh-CN', '加拿大'),
((SELECT id FROM countries WHERE code = 'MX'), 'zh-CN', '墨西哥'),
((SELECT id FROM countries WHERE code = 'GT'), 'zh-CN', '危地马拉'),
((SELECT id FROM countries WHERE code = 'BZ'), 'zh-CN', '伯利兹'),
((SELECT id FROM countries WHERE code = 'SV'), 'zh-CN', '萨尔瓦多'),
((SELECT id FROM countries WHERE code = 'HN'), 'zh-CN', '洪都拉斯'),
((SELECT id FROM countries WHERE code = 'NI'), 'zh-CN', '尼加拉瓜'),
((SELECT id FROM countries WHERE code = 'CR'), 'zh-CN', '哥斯达黎加'),
((SELECT id FROM countries WHERE code = 'PA'), 'zh-CN', '巴拿马'),

-- 南美洲国家
((SELECT id FROM countries WHERE code = 'BR'), 'zh-CN', '巴西'),
((SELECT id FROM countries WHERE code = 'AR'), 'zh-CN', '阿根廷'),
((SELECT id FROM countries WHERE code = 'CL'), 'zh-CN', '智利'),
((SELECT id FROM countries WHERE code = 'PE'), 'zh-CN', '秘鲁'),
((SELECT id FROM countries WHERE code = 'CO'), 'zh-CN', '哥伦比亚'),
((SELECT id FROM countries WHERE code = 'VE'), 'zh-CN', '委内瑞拉'),
((SELECT id FROM countries WHERE code = 'EC'), 'zh-CN', '厄瓜多尔'),
((SELECT id FROM countries WHERE code = 'BO'), 'zh-CN', '玻利维亚'),
((SELECT id FROM countries WHERE code = 'PY'), 'zh-CN', '巴拉圭'),
((SELECT id FROM countries WHERE code = 'UY'), 'zh-CN', '乌拉圭'),
((SELECT id FROM countries WHERE code = 'GY'), 'zh-CN', '圭亚那'),
((SELECT id FROM countries WHERE code = 'SR'), 'zh-CN', '苏里南'),

-- 非洲国家
((SELECT id FROM countries WHERE code = 'EG'), 'zh-CN', '埃及'),
((SELECT id FROM countries WHERE code = 'ZA'), 'zh-CN', '南非'),
((SELECT id FROM countries WHERE code = 'NG'), 'zh-CN', '尼日利亚'),
((SELECT id FROM countries WHERE code = 'KE'), 'zh-CN', '肯尼亚'),
((SELECT id FROM countries WHERE code = 'GH'), 'zh-CN', '加纳'),
((SELECT id FROM countries WHERE code = 'MA'), 'zh-CN', '摩洛哥'),
((SELECT id FROM countries WHERE code = 'TN'), 'zh-CN', '突尼斯'),
((SELECT id FROM countries WHERE code = 'DZ'), 'zh-CN', '阿尔及利亚'),
((SELECT id FROM countries WHERE code = 'LY'), 'zh-CN', '利比亚'),
((SELECT id FROM countries WHERE code = 'SD'), 'zh-CN', '苏丹'),
((SELECT id FROM countries WHERE code = 'ET'), 'zh-CN', '埃塞俄比亚'),
((SELECT id FROM countries WHERE code = 'UG'), 'zh-CN', '乌干达'),
((SELECT id FROM countries WHERE code = 'TZ'), 'zh-CN', '坦桑尼亚'),
((SELECT id FROM countries WHERE code = 'ZW'), 'zh-CN', '津巴布韦'),
((SELECT id FROM countries WHERE code = 'BW'), 'zh-CN', '博茨瓦纳'),
((SELECT id FROM countries WHERE code = 'ZM'), 'zh-CN', '赞比亚'),
((SELECT id FROM countries WHERE code = 'MW'), 'zh-CN', '马拉维'),
((SELECT id FROM countries WHERE code = 'MZ'), 'zh-CN', '莫桑比克'),
((SELECT id FROM countries WHERE code = 'NA'), 'zh-CN', '纳米比亚'),
((SELECT id FROM countries WHERE code = 'SZ'), 'zh-CN', '斯威士兰'),
((SELECT id FROM countries WHERE code = 'LS'), 'zh-CN', '莱索托'),
((SELECT id FROM countries WHERE code = 'RW'), 'zh-CN', '卢旺达'),
((SELECT id FROM countries WHERE code = 'BI'), 'zh-CN', '布隆迪'),
((SELECT id FROM countries WHERE code = 'DJ'), 'zh-CN', '吉布提'),
((SELECT id FROM countries WHERE code = 'SO'), 'zh-CN', '索马里'),
((SELECT id FROM countries WHERE code = 'ER'), 'zh-CN', '厄立特里亚'),
((SELECT id FROM countries WHERE code = 'CF'), 'zh-CN', '中非共和国'),
((SELECT id FROM countries WHERE code = 'TD'), 'zh-CN', '乍得'),
((SELECT id FROM countries WHERE code = 'CM'), 'zh-CN', '喀麦隆'),
((SELECT id FROM countries WHERE code = 'GA'), 'zh-CN', '加蓬'),
((SELECT id FROM countries WHERE code = 'GQ'), 'zh-CN', '赤道几内亚'),
((SELECT id FROM countries WHERE code = 'CG'), 'zh-CN', '刚果共和国'),
((SELECT id FROM countries WHERE code = 'CD'), 'zh-CN', '刚果民主共和国'),
((SELECT id FROM countries WHERE code = 'AO'), 'zh-CN', '安哥拉'),
((SELECT id FROM countries WHERE code = 'SN'), 'zh-CN', '塞内加尔'),
((SELECT id FROM countries WHERE code = 'ML'), 'zh-CN', '马里'),
((SELECT id FROM countries WHERE code = 'BF'), 'zh-CN', '布基纳法索'),
((SELECT id FROM countries WHERE code = 'NE'), 'zh-CN', '尼日尔'),
((SELECT id FROM countries WHERE code = 'CI'), 'zh-CN', '科特迪瓦'),
((SELECT id FROM countries WHERE code = 'LR'), 'zh-CN', '利比里亚'),
((SELECT id FROM countries WHERE code = 'SL'), 'zh-CN', '塞拉利昂'),
((SELECT id FROM countries WHERE code = 'GN'), 'zh-CN', '几内亚'),
((SELECT id FROM countries WHERE code = 'GW'), 'zh-CN', '几内亚比绍'),
((SELECT id FROM countries WHERE code = 'GM'), 'zh-CN', '冈比亚'),
((SELECT id FROM countries WHERE code = 'CV'), 'zh-CN', '佛得角'),
((SELECT id FROM countries WHERE code = 'ST'), 'zh-CN', '圣多美和普林西比'),
((SELECT id FROM countries WHERE code = 'MG'), 'zh-CN', '马达加斯加'),
((SELECT id FROM countries WHERE code = 'MU'), 'zh-CN', '毛里求斯'),
((SELECT id FROM countries WHERE code = 'SC'), 'zh-CN', '塞舌尔'),
((SELECT id FROM countries WHERE code = 'KM'), 'zh-CN', '科摩罗'),
((SELECT id FROM countries WHERE code = 'MR'), 'zh-CN', '毛里塔尼亚'),

-- 大洋洲国家
((SELECT id FROM countries WHERE code = 'AU'), 'zh-CN', '澳大利亚'),
((SELECT id FROM countries WHERE code = 'NZ'), 'zh-CN', '新西兰'),
((SELECT id FROM countries WHERE code = 'FJ'), 'zh-CN', '斐济'),
((SELECT id FROM countries WHERE code = 'PG'), 'zh-CN', '巴布亚新几内亚'),
((SELECT id FROM countries WHERE code = 'SB'), 'zh-CN', '所罗门群岛'),
((SELECT id FROM countries WHERE code = 'VU'), 'zh-CN', '瓦努阿图'),
((SELECT id FROM countries WHERE code = 'NC'), 'zh-CN', '新喀里多尼亚'),
((SELECT id FROM countries WHERE code = 'PF'), 'zh-CN', '法属波利尼西亚'),
((SELECT id FROM countries WHERE code = 'WS'), 'zh-CN', '萨摩亚'),
((SELECT id FROM countries WHERE code = 'TO'), 'zh-CN', '汤加'),
((SELECT id FROM countries WHERE code = 'KI'), 'zh-CN', '基里巴斯'),
((SELECT id FROM countries WHERE code = 'TV'), 'zh-CN', '图瓦卢'),
((SELECT id FROM countries WHERE code = 'NR'), 'zh-CN', '瑙鲁'),
((SELECT id FROM countries WHERE code = 'PW'), 'zh-CN', '帕劳'),
((SELECT id FROM countries WHERE code = 'FM'), 'zh-CN', '密克罗尼西亚联邦'),
((SELECT id FROM countries WHERE code = 'MH'), 'zh-CN', '马绍尔群岛'),

-- 加勒比海地区
((SELECT id FROM countries WHERE code = 'JM'), 'zh-CN', '牙买加'),
((SELECT id FROM countries WHERE code = 'CU'), 'zh-CN', '古巴'),
((SELECT id FROM countries WHERE code = 'HT'), 'zh-CN', '海地'),
((SELECT id FROM countries WHERE code = 'DO'), 'zh-CN', '多米尼加共和国'),
((SELECT id FROM countries WHERE code = 'TT'), 'zh-CN', '特立尼达和多巴哥'),
((SELECT id FROM countries WHERE code = 'BB'), 'zh-CN', '巴巴多斯'),
((SELECT id FROM countries WHERE code = 'LC'), 'zh-CN', '圣卢西亚'),
((SELECT id FROM countries WHERE code = 'GD'), 'zh-CN', '格林纳达'),
((SELECT id FROM countries WHERE code = 'VC'), 'zh-CN', '圣文森特和格林纳丁斯'),
((SELECT id FROM countries WHERE code = 'AG'), 'zh-CN', '安提瓜和巴布达'),
((SELECT id FROM countries WHERE code = 'DM'), 'zh-CN', '多米尼克'),
((SELECT id FROM countries WHERE code = 'KN'), 'zh-CN', '圣基茨和尼维斯'),
((SELECT id FROM countries WHERE code = 'BS'), 'zh-CN', '巴哈马'),

-- 特殊地区
((SELECT id FROM countries WHERE code = 'PR'), 'zh-CN', '波多黎各'),
((SELECT id FROM countries WHERE code = 'VI'), 'zh-CN', '美属维尔京群岛'),
((SELECT id FROM countries WHERE code = 'GU'), 'zh-CN', '关岛'),
((SELECT id FROM countries WHERE code = 'AS'), 'zh-CN', '美属萨摩亚'),
((SELECT id FROM countries WHERE code = 'MP'), 'zh-CN', '北马里亚纳群岛'),
((SELECT id FROM countries WHERE code = 'UM'), 'zh-CN', '美国本土外小岛屿'),
((SELECT id FROM countries WHERE code = 'GI'), 'zh-CN', '直布罗陀'),
((SELECT id FROM countries WHERE code = 'IM'), 'zh-CN', '马恩岛'),
((SELECT id FROM countries WHERE code = 'JE'), 'zh-CN', '泽西岛'),
((SELECT id FROM countries WHERE code = 'GG'), 'zh-CN', '根西岛'),
((SELECT id FROM countries WHERE code = 'FO'), 'zh-CN', '法罗群岛'),
((SELECT id FROM countries WHERE code = 'GL'), 'zh-CN', '格陵兰'),
((SELECT id FROM countries WHERE code = 'AX'), 'zh-CN', '奥兰群岛'),
((SELECT id FROM countries WHERE code = 'SJ'), 'zh-CN', '斯瓦尔巴群岛和扬马延岛'),
((SELECT id FROM countries WHERE code = 'BV'), 'zh-CN', '布韦岛'),
((SELECT id FROM countries WHERE code = 'HM'), 'zh-CN', '赫德岛和麦克唐纳群岛'),
((SELECT id FROM countries WHERE code = 'TF'), 'zh-CN', '法属南部领地'),
((SELECT id FROM countries WHERE code = 'IO'), 'zh-CN', '英属印度洋领地'),
((SELECT id FROM countries WHERE code = 'CC'), 'zh-CN', '科科斯群岛'),
((SELECT id FROM countries WHERE code = 'CX'), 'zh-CN', '圣诞岛'),
((SELECT id FROM countries WHERE code = 'NF'), 'zh-CN', '诺福克岛'),
((SELECT id FROM countries WHERE code = 'PN'), 'zh-CN', '皮特凯恩群岛'),
((SELECT id FROM countries WHERE code = 'SH'), 'zh-CN', '圣赫勒拿'),
((SELECT id FROM countries WHERE code = 'TC'), 'zh-CN', '特克斯和凯科斯群岛'),
((SELECT id FROM countries WHERE code = 'VG'), 'zh-CN', '英属维尔京群岛'),
((SELECT id FROM countries WHERE code = 'FK'), 'zh-CN', '福克兰群岛'),
((SELECT id FROM countries WHERE code = 'GS'), 'zh-CN', '南乔治亚岛和南桑威奇群岛');

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_country_translations_country_language ON country_translations(country_id, language);

-- 数据插入完成提示
SELECT 'Global countries data inserted successfully with Chinese translations' as status;