name: Deploy FastAPI to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # 进入项目目录
          cd /var/www/fastapi
          
          # 拉取最新代码
          git pull origin main
          
          # 停止现有容器
          docker-compose down fastapi || true
          
          # 重新构建并启动容器
          docker-compose up -d --build fastapi
          
          # 清理未使用的镜像
          docker image prune -f
          
          # 显示容器状态
          docker-compose ps 